pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - main  # Ganti jadi master jika nama branch utama kamu adalah 'master'
